// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomePageDocumentDataSlicesSlice = HeroImageSlice | VideoScrollSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

export type AllDocumentTypes = HomePageDocument;

/**
 * Primary content in *HeroImage → Default → Primary*
 */
export interface HeroImageSliceDefaultPrimary {
  /**
   * Background video field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Upload or select a video from the Media Library
   * - **API ID Path**: hero_image.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Background image field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline
   * - **API ID Path**: hero_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Supporting copy
   * - **API ID Path**: hero_image.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for HeroImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroImage*
 */
type HeroImageSliceVariation = HeroImageSliceDefault;

/**
 * HeroImage Shared Slice
 *
 * - **API ID**: `hero_image`
 * - **Description**: Full-bleed hero with a background video/image and an overlaid title and subtitle.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageSlice = prismic.SharedSlice<
  "hero_image",
  HeroImageSliceVariation
>;

/**
 * Primary content in *VideoScroll → Overlay → Primary*
 */
export interface VideoScrollSliceOverlayPrimary {
  /**
   * Background video field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Upload or select a video from the Media Library
   * - **API ID Path**: video_scroll.overlay.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Background image field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_scroll.overlay.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline
   * - **API ID Path**: video_scroll.overlay.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Scrub start field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: When the scroll-scrub begins (default: full travel)
   * - **API ID Path**: video_scroll.overlay.primary.scrub_start
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  scrub_start: prismic.SelectField<"top" | "middle">;

  /**
   * Title vertical position field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Vertical position (default: bottom)
   * - **Default Value**: bottom
   * - **API ID Path**: video_scroll.overlay.primary.title_align_vertical
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title_align_vertical: prismic.SelectField<
    "top" | "center" | "bottom",
    "filled"
  >;

  /**
   * Title horizontal position field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Horizontal position (default: left)
   * - **Default Value**: left
   * - **API ID Path**: video_scroll.overlay.primary.title_align_horizontal
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title_align_horizontal: prismic.SelectField<
    "left" | "center" | "right",
    "filled"
  >;
}

/**
 * Overlay variation for VideoScroll Slice
 *
 * - **API ID**: `overlay`
 * - **Description**: Pinned full-bleed background with an overlaid headline.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoScrollSliceOverlay = prismic.SharedSliceVariation<
  "overlay",
  Simplify<VideoScrollSliceOverlayPrimary>,
  never
>;

/**
 * Slice variation for *VideoScroll*
 */
type VideoScrollSliceVariation = VideoScrollSliceOverlay;

/**
 * VideoScroll Shared Slice
 *
 * - **API ID**: `video_scroll`
 * - **Description**: Pinned full-bleed video/image with a headline that scrolls over it.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoScrollSlice = prismic.SharedSlice<
  "video_scroll",
  VideoScrollSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroImageSlice,
      HeroImageSliceDefaultPrimary,
      HeroImageSliceVariation,
      HeroImageSliceDefault,
      VideoScrollSlice,
      VideoScrollSliceOverlayPrimary,
      VideoScrollSliceVariation,
      VideoScrollSliceOverlay,
    };
  }
}
