// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → Social Media Links*
 */
export interface FooterDocumentDataSocialMediaLinksItem {
  /**
   * Social field in *Footer → Social Media Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Linkedin
   * - **Default Value**: Linkedin
   * - **API ID Path**: footer.social_media_links[].social
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  social: prismic.SelectField<
    "Linkedin" | "Instagram" | "Youtube" | "X" | "TikTok",
    "filled"
  >;

  /**
   * Link field in *Footer → Social Media Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type FooterDocumentDataSlicesSlice = PressQuotesSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Main Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Follow our journey.
   * - **API ID Path**: footer.footer_main_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_main_title: prismic.KeyTextField;

  /**
   * Logo Footer field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo_footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_footer: prismic.ImageField<never>;

  /**
   * Social Media Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_media_links: prismic.GroupField<
    Simplify<FooterDocumentDataSocialMediaLinksItem>
  >;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | HeroImageSlice
  | VideoScrollSlice
  | DrilledStatsSlice
  | RaceBarsSlice
  | SupplyGapSlice
  | MapTargetsSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

export type AllDocumentTypes = FooterDocument | HomePageDocument;

/**
 * Item in *DrilledStats → Default → Primary → Stats (max 4)*
 */
export interface DrilledStatsSliceDefaultPrimaryStatsItem {
  /**
   * Title field in *DrilledStats → Default → Primary → Stats (max 4)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Deposits
   * - **API ID Path**: drilled_stats.default.primary.stats[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Number field in *DrilledStats → Default → Primary → Stats (max 4)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 6 or 4.1 mil (counts up on scroll)
   * - **API ID Path**: drilled_stats.default.primary.stats[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Primary content in *DrilledStats → Default → Primary*
 */
export interface DrilledStatsSliceDefaultPrimary {
  /**
   * Hide slice field in *DrilledStats → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: drilled_stats.default.primary.is_hidden
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hidden: prismic.BooleanField;

  /**
   * Title field in *DrilledStats → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline (e.g. We drilled through the stratosphere.)
   * - **API ID Path**: drilled_stats.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Feet drilled — value field in *DrilledStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 96,000 (counts up on scroll)
   * - **API ID Path**: drilled_stats.default.primary.feet_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  feet_value: prismic.KeyTextField;

  /**
   * Feet drilled — label field in *DrilledStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Feet Drilled
   * - **API ID Path**: drilled_stats.default.primary.feet_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  feet_label: prismic.KeyTextField;

  /**
   * Stats (max 4) field in *DrilledStats → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: drilled_stats.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<DrilledStatsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for DrilledStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DrilledStatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DrilledStatsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DrilledStats*
 */
type DrilledStatsSliceVariation = DrilledStatsSliceDefault;

/**
 * DrilledStats Shared Slice
 *
 * - **API ID**: `drilled_stats`
 * - **Description**: Pinned light scene: a WYSIWYG title with count-up metrics beside a drilling arrow that grows skyward on scroll. Add up to 4 stat rows.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DrilledStatsSlice = prismic.SharedSlice<
  "drilled_stats",
  DrilledStatsSliceVariation
>;

/**
 * Primary content in *HeroImage → Default → Primary*
 */
export interface HeroImageSliceDefaultPrimary {
  /**
   * Hide slice field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_image.default.primary.is_hidden
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hidden: prismic.BooleanField;

  /**
   * Background video field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Upload or select a video from the Media Library
   * - **API ID Path**: hero_image.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Background image field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline
   * - **API ID Path**: hero_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Supporting copy
   * - **API ID Path**: hero_image.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for HeroImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroImage*
 */
type HeroImageSliceVariation = HeroImageSliceDefault;

/**
 * HeroImage Shared Slice
 *
 * - **API ID**: `hero_image`
 * - **Description**: Full-bleed hero with a background video/image and an overlaid title and subtitle.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageSlice = prismic.SharedSlice<
  "hero_image",
  HeroImageSliceVariation
>;

/**
 * Item in *MapTargets → Default → Primary → Stats (max 4)*
 */
export interface MapTargetsSliceDefaultPrimaryStatsItem {
  /**
   * Title field in *MapTargets → Default → Primary → Stats (max 4)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. New Targets
   * - **API ID Path**: map_targets.default.primary.stats[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Number field in *MapTargets → Default → Primary → Stats (max 4)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 1,500 or 83% (counts up on scroll)
   * - **API ID Path**: map_targets.default.primary.stats[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Primary content in *MapTargets → Default → Primary*
 */
export interface MapTargetsSliceDefaultPrimary {
  /**
   * Hide slice field in *MapTargets → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: map_targets.default.primary.is_hidden
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hidden: prismic.BooleanField;

  /**
   * Title field in *MapTargets → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline (e.g. We operate like no other mineral exploration company.)
   * - **API ID Path**: map_targets.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *MapTargets → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Supporting paragraph shown at the bottom-left
   * - **API ID Path**: map_targets.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
   * Stats (max 4) field in *MapTargets → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: map_targets.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<MapTargetsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for MapTargets Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MapTargetsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MapTargetsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MapTargets*
 */
type MapTargetsSliceVariation = MapTargetsSliceDefault;

/**
 * MapTargets Shared Slice
 *
 * - **API ID**: `map_targets`
 * - **Description**: Pinned dark scene: a WYSIWYG title with count-up metrics and a supporting paragraph beside a continental target map whose orange markers wipe in left→right on scroll. Add up to 4 stat rows.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MapTargetsSlice = prismic.SharedSlice<
  "map_targets",
  MapTargetsSliceVariation
>;

/**
 * Primary content in *PressQuotes → Default → Primary*
 */
export interface PressQuotesSliceDefaultPrimary {
  /**
   * Hide slice field in *PressQuotes → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: press_quotes.default.primary.is_hidden
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hidden: prismic.BooleanField;

  /**
   * Image field in *PressQuotes → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: press_quotes.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Date field in *PressQuotes → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Publication date
   * - **API ID Path**: press_quotes.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Title field in *PressQuotes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Quote or headline
   * - **API ID Path**: press_quotes.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Link field in *PressQuotes → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to the article
   * - **API ID Path**: press_quotes.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for PressQuotes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PressQuotesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PressQuotesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PressQuotes*
 */
type PressQuotesSliceVariation = PressQuotesSliceDefault;

/**
 * PressQuotes Shared Slice
 *
 * - **API ID**: `press_quotes`
 * - **Description**: A single press item — publication image, date, quote/title and a link to the article. Add one per quote.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PressQuotesSlice = prismic.SharedSlice<
  "press_quotes",
  PressQuotesSliceVariation
>;

/**
 * Item in *RaceBars → Default → Primary → Metric groups → Rows*
 */
export interface RaceBarsSliceDefaultPrimaryItemsRowsItem {
  /**
   * Row label field in *RaceBars → Default → Primary → Metric groups → Rows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. EARTH AI
   * - **API ID Path**: race_bars.default.primary.items[].rows[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value (counts up on scroll) field in *RaceBars → Default → Primary → Metric groups → Rows*
   *
   * - **Field Type**: Number
   * - **Placeholder**: e.g. 3
   * - **API ID Path**: race_bars.default.primary.items[].rows[].value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  value: prismic.NumberField;

  /**
   * Highlight (orange treatment) field in *RaceBars → Default → Primary → Metric groups → Rows*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: race_bars.default.primary.items[].rows[].highlight
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight: prismic.BooleanField;
}

/**
 * Item in *RaceBars → Default → Primary → Metric groups*
 */
export interface RaceBarsSliceDefaultPrimaryItemsItem {
  /**
   * Metric label field in *RaceBars → Default → Primary → Metric groups*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. DISCOVERY TIMELINE
   * - **API ID Path**: race_bars.default.primary.items[].metric
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metric: prismic.KeyTextField;

  /**
   * Unit field in *RaceBars → Default → Primary → Metric groups*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. YEARS or %
   * - **API ID Path**: race_bars.default.primary.items[].unit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  unit: prismic.KeyTextField;

  /**
   * Rows field in *RaceBars → Default → Primary → Metric groups*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: race_bars.default.primary.items[].rows[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  rows: prismic.NestedGroupField<
    Simplify<RaceBarsSliceDefaultPrimaryItemsRowsItem>
  >;
}

/**
 * Primary content in *RaceBars → Default → Primary*
 */
export interface RaceBarsSliceDefaultPrimary {
  /**
   * Hide slice field in *RaceBars → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: race_bars.default.primary.is_hidden
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hidden: prismic.BooleanField;

  /**
   * Heading field in *RaceBars → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline (e.g. Incumbents created the problem…)
   * - **API ID Path**: race_bars.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Metric groups field in *RaceBars → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: race_bars.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<RaceBarsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for RaceBars Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RaceBarsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RaceBarsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RaceBars*
 */
type RaceBarsSliceVariation = RaceBarsSliceDefault;

/**
 * RaceBars Shared Slice
 *
 * - **API ID**: `race_bars`
 * - **Description**: Animated metric-vs-metric comparison: bars grow left→right and numbers count up the first time the section scrolls into view. Add metric groups, each with rows; mark the EARTH AI row as highlighted for the orange treatment.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RaceBarsSlice = prismic.SharedSlice<
  "race_bars",
  RaceBarsSliceVariation
>;

/**
 * Item in *SupplyGap → Default → Primary → Y-axis ticks (low → high)*
 */
export interface SupplyGapSliceDefaultPrimaryYTicksItem {
  /**
   * Tick field in *SupplyGap → Default → Primary → Y-axis ticks (low → high)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 10
   * - **API ID Path**: supply_gap.default.primary.y_ticks[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *SupplyGap → Default → Primary → X-axis labels (left → right)*
 */
export interface SupplyGapSliceDefaultPrimaryXLabelsItem {
  /**
   * Label field in *SupplyGap → Default → Primary → X-axis labels (left → right)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 2030
   * - **API ID Path**: supply_gap.default.primary.x_labels[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *SupplyGap → Default → Primary → Demand endpoint (counts up)*
 */
export interface SupplyGapSliceDefaultPrimaryDemandItem {
  /**
   * Label field in *SupplyGap → Default → Primary → Demand endpoint (counts up)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. DEMAND
   * - **API ID Path**: supply_gap.default.primary.demand[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *SupplyGap → Default → Primary → Demand endpoint (counts up)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 1270
   * - **API ID Path**: supply_gap.default.primary.demand[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *SupplyGap → Default → Primary → Supply endpoint (counts up)*
 */
export interface SupplyGapSliceDefaultPrimarySupplyItem {
  /**
   * Label field in *SupplyGap → Default → Primary → Supply endpoint (counts up)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. CURRENT AND DEVELOPING MINES
   * - **API ID Path**: supply_gap.default.primary.supply[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *SupplyGap → Default → Primary → Supply endpoint (counts up)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 627
   * - **API ID Path**: supply_gap.default.primary.supply[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Primary content in *SupplyGap → Default → Primary*
 */
export interface SupplyGapSliceDefaultPrimary {
  /**
   * Hide slice field in *SupplyGap → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: supply_gap.default.primary.is_hidden
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hidden: prismic.BooleanField;

  /**
   * Heading field in *SupplyGap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline (e.g. Demand is set, but supply is uncertain.)
   * - **API ID Path**: supply_gap.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *SupplyGap → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Supporting paragraph shown beside the heading
   * - **API ID Path**: supply_gap.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
   * Y-axis ticks (low → high) field in *SupplyGap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: supply_gap.default.primary.y_ticks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  y_ticks: prismic.GroupField<Simplify<SupplyGapSliceDefaultPrimaryYTicksItem>>;

  /**
   * X-axis labels (left → right) field in *SupplyGap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: supply_gap.default.primary.x_labels[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  x_labels: prismic.GroupField<
    Simplify<SupplyGapSliceDefaultPrimaryXLabelsItem>
  >;

  /**
   * Demand endpoint (counts up) field in *SupplyGap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: supply_gap.default.primary.demand[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  demand: prismic.GroupField<Simplify<SupplyGapSliceDefaultPrimaryDemandItem>>;

  /**
   * Supply endpoint (counts up) field in *SupplyGap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: supply_gap.default.primary.supply[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  supply: prismic.GroupField<Simplify<SupplyGapSliceDefaultPrimarySupplyItem>>;
}

/**
 * Default variation for SupplyGap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SupplyGapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SupplyGapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SupplyGap*
 */
type SupplyGapSliceVariation = SupplyGapSliceDefault;

/**
 * SupplyGap Shared Slice
 *
 * - **API ID**: `supply_gap`
 * - **Description**: Pinned demand-vs-supply chart: both curves and their gradient fills wipe in left→right and the two endpoint figures count up as the section scrolls. The deficit reads as the band between the curves.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SupplyGapSlice = prismic.SharedSlice<
  "supply_gap",
  SupplyGapSliceVariation
>;

/**
 * Primary content in *VideoScroll → Overlay → Primary*
 */
export interface VideoScrollSliceOverlayPrimary {
  /**
   * Hide slice field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_scroll.overlay.primary.is_hidden
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hidden: prismic.BooleanField;

  /**
   * Background video field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Upload or select a video from the Media Library
   * - **API ID Path**: video_scroll.overlay.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Background image field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_scroll.overlay.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Headline
   * - **API ID Path**: video_scroll.overlay.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Scrub start field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: When the scroll-scrub begins (default: full travel)
   * - **API ID Path**: video_scroll.overlay.primary.scrub_start
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  scrub_start: prismic.SelectField<"top" | "middle">;

  /**
   * Title vertical position field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Vertical position (default: bottom)
   * - **Default Value**: bottom
   * - **API ID Path**: video_scroll.overlay.primary.title_align_vertical
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title_align_vertical: prismic.SelectField<
    "top" | "center" | "bottom",
    "filled"
  >;

  /**
   * Title horizontal position field in *VideoScroll → Overlay → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Horizontal position (default: left)
   * - **Default Value**: left
   * - **API ID Path**: video_scroll.overlay.primary.title_align_horizontal
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title_align_horizontal: prismic.SelectField<
    "left" | "center" | "right",
    "filled"
  >;
}

/**
 * Overlay variation for VideoScroll Slice
 *
 * - **API ID**: `overlay`
 * - **Description**: Pinned full-bleed background with an overlaid headline.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoScrollSliceOverlay = prismic.SharedSliceVariation<
  "overlay",
  Simplify<VideoScrollSliceOverlayPrimary>,
  never
>;

/**
 * Slice variation for *VideoScroll*
 */
type VideoScrollSliceVariation = VideoScrollSliceOverlay;

/**
 * VideoScroll Shared Slice
 *
 * - **API ID**: `video_scroll`
 * - **Description**: Pinned full-bleed video/image with a headline that scrolls over it.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoScrollSlice = prismic.SharedSlice<
  "video_scroll",
  VideoScrollSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialMediaLinksItem,
      FooterDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      DrilledStatsSlice,
      DrilledStatsSliceDefaultPrimaryStatsItem,
      DrilledStatsSliceDefaultPrimary,
      DrilledStatsSliceVariation,
      DrilledStatsSliceDefault,
      HeroImageSlice,
      HeroImageSliceDefaultPrimary,
      HeroImageSliceVariation,
      HeroImageSliceDefault,
      MapTargetsSlice,
      MapTargetsSliceDefaultPrimaryStatsItem,
      MapTargetsSliceDefaultPrimary,
      MapTargetsSliceVariation,
      MapTargetsSliceDefault,
      PressQuotesSlice,
      PressQuotesSliceDefaultPrimary,
      PressQuotesSliceVariation,
      PressQuotesSliceDefault,
      RaceBarsSlice,
      RaceBarsSliceDefaultPrimaryItemsRowsItem,
      RaceBarsSliceDefaultPrimaryItemsItem,
      RaceBarsSliceDefaultPrimary,
      RaceBarsSliceVariation,
      RaceBarsSliceDefault,
      SupplyGapSlice,
      SupplyGapSliceDefaultPrimaryYTicksItem,
      SupplyGapSliceDefaultPrimaryXLabelsItem,
      SupplyGapSliceDefaultPrimaryDemandItem,
      SupplyGapSliceDefaultPrimarySupplyItem,
      SupplyGapSliceDefaultPrimary,
      SupplyGapSliceVariation,
      SupplyGapSliceDefault,
      VideoScrollSlice,
      VideoScrollSliceOverlayPrimary,
      VideoScrollSliceVariation,
      VideoScrollSliceOverlay,
    };
  }
}
