// Generated by Prismic, then completed with the project's current slice set so
// the static SliceZone keeps rendering. (Slice Machine may rewrite this when the
// Prismic models are connected — re-add any missing entries if it does.)

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  hero_image:      defineAsyncComponent(() => import("./HeroImage/index.vue")),
  video_scroll:    defineAsyncComponent(() => import("./VideoScroll/index.vue")),
  video_scroll_titles: defineAsyncComponent(() => import("./VideoScrollTitles/index.vue")),
  race_bars:       defineAsyncComponent(() => import("./RaceBars/index.vue")),
  supply_gap:      defineAsyncComponent(() => import("./SupplyGap/index.vue")),
  drilled_stats:   defineAsyncComponent(() => import("./DrilledStats/index.vue")),
  map_targets:     defineAsyncComponent(() => import("./MapTargets/index.vue")),
  wysiwyg:         defineAsyncComponent(() => import("./Wysiwyg/index.vue")),
  feature_media:   defineAsyncComponent(() => import("./FeatureMedia/index.vue")),
  cta:             defineAsyncComponent(() => import("./Cta/index.vue")),
  press_quotes:    defineAsyncComponent(() => import("./PressQuotes/index.vue")),
});
