// Generated by Prismic, then completed with the project's current slice set so
// the static SliceZone keeps rendering. (Slice Machine may rewrite this when the
// Prismic models are connected — re-add any missing entries if it does.)

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  hero_image:      defineAsyncComponent(() => import("./HeroImage/index.vue")),
  scroll_video:    defineAsyncComponent(() => import("./ScrollVideo/index.vue")),
  image_text:      defineAsyncComponent(() => import("./ImageText/index.vue")),
  supply_chart:    defineAsyncComponent(() => import("./SupplyChart/index.vue")),
  comparison_bars: defineAsyncComponent(() => import("./ComparisonBars/index.vue")),
  stats_row:       defineAsyncComponent(() => import("./StatsRow/index.vue")),
  wysiwyg:         defineAsyncComponent(() => import("./Wysiwyg/index.vue")),
  feature_media:   defineAsyncComponent(() => import("./FeatureMedia/index.vue")),
  cta:             defineAsyncComponent(() => import("./Cta/index.vue")),
});
